# Generated by Django 2.2.8 on 2023-12-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='short_text',
            new_name='content',
        ),
    ]
